### PR TITLE
[update] use latest PDFjs lib

### PR DESCRIPTION
**Pull request by lVeliarl**
Use the latest PDF.js lib for better PDF document rendering in our PDF Viewer. Our core lib has to be updated before this update is pushed to master/CDN (see https://git.webix.io/Webix/core/pulls/377).

Here in particular we are using the latest version (4.7.76 at the moment), https://github.com/mozilla/pdf.js/releases/tag/v4.7.76, specifically the legacy build for better browser support (see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support). Additionally, all files have been minified separately via terser (the authors do not provide minified files by default).

### CODE REVIEW

**Comment by mkozhukh** [comment]
What is the reason for including .mjs versions ? are they used by Webix ?

**Comment by lVeliarl** [comment]
> What is the reason for including .mjs versions ? are they used by Webix ?

Well, the build includes .mjs files only. Simply changing the extension to .js doesn't seem to work (since it's basically still a module, but without us knowing about it explicitly). In order to support .mjs files I've also updated our require() method to support resources with `type="module"` (i.e., .mjs extension is treated as a ES module).

**Comment by lVeliarl** [comment]
Update: restored the old version to preserve backwards compatibility and updated the paths for the new version.

**Comment by lVeliarl** [comment]
Restored the old version to preserve backwards compatibility and updated the paths for the new version.

**Pull request merged**
